server:
  port: 8010

spring:
  application:
    name: microservice-consumer-movie-ribbon

eureka:
  client:
    service-url:
      default-zone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
