server:
  port: 8020
spring:
  application:
    name: microservice-consumer-movie-feign
eureka:
  client:
    service-url:
      default-zone: http://discovery:8761/eureka/
  instance:
    prefer-ip-address: true
ribbon:
  eureka:
    enabled: true
